name: LuemmelPlugin
version: '${project.version}'
main: de.leon.luemmelplugin.LuemmelPlugin
api-version: '1.20'

commands:
  vote:
    description: Create a Vote for World time/weather
    usage: "Usage: /vote [yes|no|day|night|sun]"
    aliases:
    permission: luemmel.vote.*, luemmel.vote.sun, luemmel.vote.night, luemmel.vote.day